# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubComment < Formula
  desc "CLI to create and hide GitHub comments
"
  homepage "https://github.com/suzuki-shunsuke/github-comment"
  version "5.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.0/github-comment_5.0.0_darwin_amd64.tar.gz"
      sha256 "3b0834f1504f8e3c3b797507aca010d2bd9be394cded30e63e99d061ddf519c2"

      def install
        bin.install "github-comment"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.0/github-comment_5.0.0_darwin_arm64.tar.gz"
      sha256 "4b146a8685938cc93ead98876eed3ba6fe236ca3739992447f685b59d82f4e34"

      def install
        bin.install "github-comment"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.0/github-comment_5.0.0_linux_arm64.tar.gz"
      sha256 "651641f36d4b8bf94f786681e1de61cbb65ea21b2666c8fa6b975d1cd000d40e"

      def install
        bin.install "github-comment"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.0/github-comment_5.0.0_linux_amd64.tar.gz"
      sha256 "1da8cb9d52395018ec15f876347e204fe632c833baa1831ca36302dec1e0f97a"

      def install
        bin.install "github-comment"
      end
    end
  end

  test do
    system "#{bin}/github-comment --version"
  end
end
