# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubComment < Formula
  desc "CLI to create and hide GitHub comments
"
  homepage "https://github.com/suzuki-shunsuke/github-comment"
  version "5.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.1/github-comment_5.0.1_darwin_arm64.tar.gz"
      sha256 "89e34ee4d89cea1721525ccd5581486889a48335dbaec4c330e3ad655828e2c2"

      def install
        bin.install "github-comment"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.1/github-comment_5.0.1_darwin_amd64.tar.gz"
      sha256 "a37f518cebbcb79fdfd2910db0305b08c58a97ed783c9499e513a4fe2f2b7aaa"

      def install
        bin.install "github-comment"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.1/github-comment_5.0.1_linux_arm64.tar.gz"
      sha256 "4530230dc20a0662da1d5e64e7095587003a2df91a245f18bf7aa4a702c83918"

      def install
        bin.install "github-comment"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v5.0.1/github-comment_5.0.1_linux_amd64.tar.gz"
      sha256 "e903b06482e310f7f147bd67a772295aec7918411198acfe3e6d0bd71041ca7a"

      def install
        bin.install "github-comment"
      end
    end
  end

  test do
    system "#{bin}/github-comment --version"
  end
end
