# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-comment" do
  desc "CLI to create and hide GitHub comments
"
  homepage "https://github.com/suzuki-shunsuke/github-comment"
  version "6.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-comment"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v6.3.3/github-comment_6.3.3_darwin_amd64.tar.gz"
      sha256 "7fce0fa45e18aa13f90dd4ba2d148e9684c0b55e3706f00e22327d161ca73e9e"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v6.3.3/github-comment_6.3.3_darwin_arm64.tar.gz"
      sha256 "c46a68b874f71be892162f733b66cf4cb1c3288fc14e52fe9579a7588ffb73dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v6.3.3/github-comment_6.3.3_linux_amd64.tar.gz"
      sha256 "2a5e4b3dac2dd659b23fc9a3beca7f5cceff98b8c4c0e2bd82bd6c60dbf84e03"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v6.3.3/github-comment_6.3.3_linux_arm64.tar.gz"
      sha256 "954954f558b90b51b6202833196416d388a43de5fa41be9246bade0ca0ebc7dc"
    end
  end

  # No zap stanza required
end
