# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-comment" do
  name "github-comment"
  desc "CLI to create and hide GitHub comments
"
  homepage "https://github.com/suzuki-shunsuke/github-comment"
  version "6.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-comment"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_darwin_amd64.tar.gz"
      sha256 "5b37bb20946636ea938a5a6be145beb2fe2232867edaa5752b105c34b31d0461"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_darwin_arm64.tar.gz"
      sha256 "7af5ed1bf9c78892da02d3383cef1404025de099871b4bdacef9b73baf360752"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_linux_amd64.tar.gz"
      sha256 "df2cc573653a632f3245a24f20fc7a15a8096b7b42c599c489c7e2cd3e3c48c8"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_linux_arm64.tar.gz"
      sha256 "a666da1c16ffb7ac54f6a9a0d92118950a847aa216c0a1b08bf6ba503206c01c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-comment"]
    end
  end

  # No zap stanza required
end
