# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-comment" do
  name "github-comment"
  desc "CLI to create and hide GitHub comments
"
  homepage "https://github.com/suzuki-shunsuke/github-comment"
  version "6.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-comment"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_darwin_amd64.tar.gz"
      sha256 "ae36c77af8b341ec8a6acac83ba68641dcc933b3571de6f213f7970993ca88fa"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_darwin_arm64.tar.gz"
      sha256 "41824cdccbeccebec0a0acb3388a8951e1d7300f6c912c392d347ed76a0f02d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_linux_amd64.tar.gz"
      sha256 "2e5090cd77be1c8aece9390030a9c12b157e08535f757223ad2317ff7382a411"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/github-comment/releases/download/v#{version}/github-comment_#{version}_linux_arm64.tar.gz"
      sha256 "b74418dbd5da1d1fb257aa60d639c2011347b438909560910a8f52c4ae371aab"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-comment"]
    end
  end

  # No zap stanza required
end
